### ISSUE TITLE
Priority: Table Component, test, and story

### ISSUE THREAD

**Issue by KateUnger** [ucsb-cs156-f23/proj-courses-f23-7pm-3#14]
- Create a table component that displays two columns; one for the Enroll code, and one for Quarter in QYY format. 
- This table will be displayed on the CourseDetails page.
- No need to add the rest of the fields, that data will be added in issue #23

**Comment by pconrad** [comment]
@KateUnger Can you clarify what this issue is in service of? 

What's the user story here?  As  a user, I can____ so that ____ ?
